"""Ship git activity to ooptdd as structured logs — instead of email.

Git events (commit / merge / checkout / rebase-rewrite / push) become ooptdd structured
events so they land in your log store and feed the agent loop, rather than a mailbox.

Two halves:

* ``emit(op)`` — called by the installed git hooks. Builds a ``git.<op>`` event, **always**
  appends it to a local JSONL capture (durable with zero infra), and additionally **ships to
  the ooptdd backend** (OpenObserve) when ``OOPTDD_OO_URL`` is set. Never raises.
* ``install()`` — writes hook scripts to a global hooks dir and points
  ``git config --global core.hooksPath`` at it, so **every repo on this machine** logs git
  activity to ooptdd. ``uninstall()`` / ``status()`` manage it.

Design rule: **never block git**. Every failure is swallowed and the hooks always ``exit 0``.

Config (all optional, env):
    OOPTDD_GIT_LOG        local capture path (default $XDG_STATE_HOME/ooptdd/git-events.jsonl)
    OOPTDD_OO_URL/...     when set, also ship to OpenObserve via ooptdd's backend
    OOPTDD_OO_STREAM      OpenObserve stream for git events (default "git")
    OOPTDD_GIT_SERVICE    the event `service` field (default "git")
    OOPTDD_GIT_HOOKS_DIR  where install() writes hooks (default $XDG_CONFIG_HOME/git/ooptdd-hooks)
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

# git hook filename -> the op label we log under
_HOOK_OPS = {
    "post-commit": "commit",
    "post-merge": "merge",
    "post-checkout": "checkout",
    "post-rewrite": "rewrite",
    "pre-push": "push",
}

# The hook runs git_hooks.py *as a standalone script by path* (not `python -m ooptdd_loop…`)
# on purpose: a hook must not pull in the heavy ooptdd_loop package __init__ (slower, and it
# would silently stop logging if any unrelated sibling import breaks). This file only needs
# stdlib at import; ooptdd is imported lazily and optionally inside _ship_remote.
_HOOK_TEMPLATE = (
    "#!/bin/sh\n"
    "# ooptdd git logging hook (auto-generated by ooptdd_loop.git_hooks) — never blocks git.\n"
    '"{py}" "{script}" emit {op} >/dev/null 2>&1 || true\n'
    "exit 0\n"
)


def _git(args: list[str], cwd: str | None = None) -> str | None:
    """Run ``git <args>``; stripped stdout or ``None`` on any failure. Never raises."""
    try:
        out = subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, timeout=5)
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout.strip() or None if out.returncode == 0 else None


def _normalize_remote(url: str | None) -> str | None:
    """``host/owner/repo`` from a remote URL (scheme/user/port/.git stripped); ``None`` if not a URL."""
    if not url:
        return None
    u = url.strip()
    m = re.match(r"^[\w.+-]+@([^:/]+):(.+)$", u)  # scp-like git@host:owner/repo.git
    if not m:
        m = re.match(r"^[a-zA-Z][\w+.-]*://(?:[^@/]+@)?([^/:]+)(?::\d+)?/(.+)$", u)
    if not m:
        return None
    path = re.sub(r"\.git$", "", m.group(2)).strip("/")
    return f"{m.group(1).lower()}/{path}" if path else None


def _repo_id(top: str | None, cwd: str | None) -> str:
    rid = _normalize_remote(_git(["config", "--get", "remote.origin.url"], cwd))
    return rid or (os.path.basename(top) if top else "unknown")


def capture_path() -> Path:
    """Local durable JSONL capture path (per-machine state, never a repo)."""
    explicit = os.getenv("OOPTDD_GIT_LOG")
    if explicit:
        return Path(explicit).expanduser()
    base = os.getenv("XDG_STATE_HOME")
    root = Path(base).expanduser() if base else Path.home() / ".local" / "state"
    return root / "ooptdd" / "git-events.jsonl"


def hooks_dir() -> Path:
    explicit = os.getenv("OOPTDD_GIT_HOOKS_DIR")
    if explicit:
        return Path(explicit).expanduser()
    base = os.getenv("XDG_CONFIG_HOME")
    root = Path(base).expanduser() if base else Path.home() / ".config"
    return root / "git" / "ooptdd-hooks"


def build_event(op: str, *, cwd: str | None = None, extra: dict | None = None) -> dict:
    """A git.<op> ooptdd event envelope (cid = repo identity, so a repo's events correlate)."""
    top = _git(["rev-parse", "--show-toplevel"], cwd)
    rid = _repo_id(top, cwd)
    ev = {
        "event": f"git.{op}",
        # three correlation aliases ooptdd backends accept; cid = repo identity
        "cid": rid, "correlation_id": rid, "cycle_id": rid,
        "service": os.getenv("OOPTDD_GIT_SERVICE", "git"),
        "level": "INFO",
        "_timestamp": int(time.time() * 1_000_000),
        "ts": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "op": op,
        "repo": os.path.basename(top) if top else None,
        "repo_id": rid,
        "branch": _git(["rev-parse", "--abbrev-ref", "HEAD"], cwd),
        "commit": _git(["rev-parse", "HEAD"], cwd),
        "author": _git(["log", "-1", "--format=%an <%ae>"], cwd),
    }
    host = getattr(os, "uname", lambda: None)()
    if host is not None:
        ev["host"] = host.nodename
    if op == "commit":
        ev["subject"] = _git(["log", "-1", "--format=%s"], cwd)
    if extra:
        ev.update(extra)
    return ev


def _append_local(ev: dict) -> None:
    try:
        p = capture_path()
        p.parent.mkdir(parents=True, exist_ok=True)
        with p.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(ev, ensure_ascii=False) + "\n")
    except Exception:
        pass  # local capture is best-effort; never break git


def _ship_remote(ev: dict) -> None:
    if not os.getenv("OOPTDD_OO_URL"):
        return  # no store configured -> JSONL capture only
    try:
        from ooptdd.backends import get_backend

        get_backend("openobserve", stream=os.getenv("OOPTDD_OO_STREAM", "git")).ship([ev])
    except Exception:
        pass  # ship is best-effort; the JSONL capture still has the event


def emit(op: str, *, cwd: str | None = None, extra: dict | None = None) -> dict | None:
    """Build + record a git.<op> event. Local JSONL always; OpenObserve when configured.
    Returns the event (for tests/callers) or ``None`` if it could not be built. Never raises."""
    try:
        ev = build_event(op, cwd=cwd, extra=extra)
    except Exception:
        return None
    _append_local(ev)
    _ship_remote(ev)
    return ev


# ── install / uninstall / status ─────────────────────────────────────────────


def install(*, python: str | None = None, script: str | None = None,
            set_hooks_path: bool = True) -> Path:
    """Write the git hooks and (by default) point global core.hooksPath at them.

    Hooks invoke this file by absolute path with ``python`` (default: the current
    interpreter, which must be able to ``import ooptdd`` for the optional OpenObserve ship).
    """
    py = python or sys.executable
    src = script or os.path.abspath(__file__)
    d = hooks_dir()
    d.mkdir(parents=True, exist_ok=True)
    for hook, op in _HOOK_OPS.items():
        f = d / hook
        f.write_text(_HOOK_TEMPLATE.format(py=py, script=src, op=op), encoding="utf-8")
        f.chmod(0o755)
    if set_hooks_path:
        subprocess.run(["git", "config", "--global", "core.hooksPath", str(d)], check=False)
    return d


def uninstall(*, set_hooks_path: bool = True) -> None:
    """Unset global core.hooksPath if it points at our dir; leave hook files + capture in place."""
    if set_hooks_path:
        cur = _git(["config", "--global", "core.hooksPath"])
        if cur and Path(cur).expanduser().resolve() == hooks_dir().resolve():
            subprocess.run(["git", "config", "--global", "--unset", "core.hooksPath"], check=False)


def status() -> dict:
    cur = _git(["config", "--global", "core.hooksPath"])
    cap = capture_path()
    lines = 0
    try:
        with cap.open(encoding="utf-8") as fh:
            lines = sum(1 for _ in fh)
    except OSError:
        pass
    installed = bool(cur) and Path(cur).expanduser().resolve() == hooks_dir().resolve()
    return {"hooks_dir": str(hooks_dir()), "core_hooksPath": cur, "installed": installed,
            "capture": str(cap), "captured_events": lines,
            "remote_ship": "openobserve" if os.getenv("OOPTDD_OO_URL") else "off (set OOPTDD_OO_URL)"}


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    cmd = args[0] if args else ""
    if cmd == "emit":
        emit(args[1] if len(args) > 1 else "unknown")
        return 0
    if cmd == "install":
        d = install()
        print(f"ooptdd git logging installed: hooks in {d}; git core.hooksPath set globally.")
        print(f"local capture: {capture_path()}  (set OOPTDD_OO_URL to also ship to OpenObserve)")
        return 0
    if cmd == "uninstall":
        uninstall()
        print("ooptdd git logging uninstalled (core.hooksPath unset; files kept).")
        return 0
    if cmd == "status":
        for k, v in status().items():
            print(f"{k}: {v}")
        return 0
    print("usage: python -m ooptdd_loop.git_hooks {emit <op>|install|uninstall|status}",
          file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
